group=org.nebula
mcVersion=26.1.2
apiVersion=26.1.2
channel=DEV

# Paper commit used by Folia 26.1.x
paperRef=b4682bfef616ac62e73cc96046dacdf4a6f53eeb

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
org.gradle.java.installations.paths=/usr/lib/jvm/java-25-openjdk-amd64
