package org.nebula.core.scheduler;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Implements the {@code ExtendDAG_ForMicroStep} algorithm (arch doc §2.3).
 *
 * <p>After each logical execution wave, completed tasks may trigger new
 * downstream tasks (e.g. redstone wire updating adjacent wires).  This class
 * iteratively extends the mutable graph until either no new tasks are generated
 * (fixed point) or the hard cap {@code MAX_MICRO_STEPS} is reached.
 *
 * <p>Conflict resolution:
 * <ul>
 *   <li>New task conflicts with an <em>unexecuted</em> task → add dependency edge.</li>
 *   <li>New task conflicts with an <em>already-executed</em> task → mark as
 *       "conflict-deferred": excluded from this tick, returned as the
 *       next-tick seed set.</li>
 * </ul>
 *
 * <p>Thread-safety: instances are not thread-safe; create one per tick.
 */
public final class MicroStepExtender {

    /** Hard cap on within-tick microstep iterations (arch doc §2.3). */
    public static final int MAX_MICRO_STEPS = 256;

    private final TaskGenerator generator;
    private final int maxMicroSteps;

    // Mutable graph state maintained across microstep rounds
    private final Map<String, TaskNode> tasks = new LinkedHashMap<>();
    private final Set<DependencyEdge> edges = new LinkedHashSet<>();
    private final Set<String> executed = new LinkedHashSet<>();

    // Tasks that conflicted with already-executed tasks → deferred to next tick
    private final List<TaskNode> deferredToNextTick = new ArrayList<>();

    private int microStepCount = 0;

    public MicroStepExtender(TaskGenerator generator) {
        this(generator, MAX_MICRO_STEPS);
    }

    public MicroStepExtender(TaskGenerator generator, int maxMicroSteps) {
        this.generator = generator;
        this.maxMicroSteps = maxMicroSteps;
    }

    /**
     * Seeds the extender with the initial task graph that has already been built
     * for this tick (before any microstep expansion).
     */
    public void seed(TaskGraph initialGraph) {
        tasks.putAll(initialGraph.tasks());
        edges.addAll(initialGraph.edges());
    }

    /**
     * Records that {@code taskId} has been executed (its writes are now visible).
     * Must be called by the executor after each task completes.
     */
    public void markExecuted(String taskId) {
        executed.add(taskId);
    }

    /**
     * Extends the DAG with tasks generated by the completed trigger tasks.
     *
     * <p>Should be called after each execution layer completes, passing the
     * task IDs that were in that layer.
     *
     * <p>Conflict resolution for generated tasks:
     * <ul>
     *   <li>Conflict with the trigger that generated this task → dependency is already
     *       satisfied (trigger completed), so the edge is recorded but task is NOT deferred.</li>
     *   <li>Conflict with another already-executed task (not a trigger) → defer to next tick.</li>
     *   <li>Conflict with a pending (unexecuted) task → add dependency edge.</li>
     * </ul>
     *
     * @param triggerIds task IDs that completed in the most recent layer
     * @return {@code true} if new tasks were added (more layers may be needed),
     *         {@code false} if the fixed point has been reached
     * @throws MicroStepLimitException if {@link #MAX_MICRO_STEPS} is exceeded
     */
    public boolean extend(List<String> triggerIds) {
        if (microStepCount >= maxMicroSteps) {
            throw new MicroStepLimitException(microStepCount,
                "MAX_MICRO_STEPS=" + maxMicroSteps + " exceeded — check for abnormal circuit or bug");
        }

        Set<String> triggerSet = new java.util.HashSet<>(triggerIds);

        List<TaskNode> newTasks = new ArrayList<>();
        for (String triggerId : triggerIds) {
            TaskNode trigger = tasks.get(triggerId);
            if (trigger == null) continue;
            List<TaskNode> generated = generator.generateFrom(trigger);
            for (TaskNode candidate : generated) {
                if (tasks.containsKey(candidate.taskId())) {
                    continue; // already in graph
                }
                newTasks.add(candidate);
            }
        }

        if (newTasks.isEmpty()) {
            return false; // fixed point
        }

        microStepCount++;

        // For each new task, resolve conflicts against existing tasks
        for (TaskNode newTask : newTasks) {
            boolean deferred = false;
            List<DependencyEdge> newEdges = new ArrayList<>();

            for (TaskNode existing : tasks.values()) {
                List<DependencyEdge> conflicts = RWConflictDetector.edgesFor(newTask, existing);
                if (conflicts.isEmpty()) continue;

                if (executed.contains(existing.taskId())) {
                    if (triggerSet.contains(existing.taskId())
                            && allRawFromTrigger(conflicts, existing.taskId())) {
                        // All conflicts with this trigger are RAW (new task reads trigger's output).
                        // Dependency is already satisfied — trigger completed and committed.
                        newEdges.addAll(conflicts);
                    } else {
                        // WAW/WAR conflict with executed task → defer to next tick
                        deferred = true;
                        break;
                    }
                } else {
                    // Conflict with pending task → add dependency edges
                    newEdges.addAll(conflicts);
                }
            }

            if (deferred) {
                deferredToNextTick.add(newTask);
            } else {
                tasks.put(newTask.taskId(), newTask);
                edges.addAll(newEdges);
            }
        }

        return true;
    }

    /**
     * Snapshots the current (extended) graph as an immutable {@link TaskGraph}.
     * The graph reflects all microstep extensions applied so far.
     */
    public TaskGraph currentGraph() {
        return new TaskGraph(Map.copyOf(tasks), Set.copyOf(edges));
    }

    /**
     * Tasks that were deferred because they conflicted with already-executed work.
     * These should be fed as the initial dirty set for the next tick.
     */
    public List<TaskNode> deferredToNextTick() {
        return List.copyOf(deferredToNextTick);
    }

    /** How many microstep rounds have been performed. */
    public int microStepCount() {
        return microStepCount;
    }

    /**
     * Returns true if all conflict edges involving the given trigger are RAW
     * (new task reads what trigger wrote). WAW/WAR conflicts are not safe to
     * treat as satisfied — they represent true write conflicts.
     */
    private static boolean allRawFromTrigger(List<DependencyEdge> conflicts, String triggerId) {
        for (DependencyEdge edge : conflicts) {
            if (edge.sourceTaskId().equals(triggerId) || edge.targetTaskId().equals(triggerId)) {
                if (edge.type() != DependencyType.RAW) {
                    return false;
                }
            }
        }
        return true;
    }
}
