package org.nebula.core.state;

public enum EventType {
    BLOCK_UPDATE,
    ENTITY_MOVED,
    ENTITY_SPAWNED,
    ENTITY_INTERACTED,
    PLAYER_MOVED,
    PLAYER_HEALTH_CHANGED,
    PLAYER_HUNGER_CHANGED,
    INVENTORY_CHANGED,
    GLOBAL_STATE_CHANGED
}
