package org.nebula.maintenance.asm;

import java.util.Objects;

/**
 * The signature information extracted from one method declaration in a JVM
 * {@code .class} file (Phase 1.5, NEBULA-PATCH-2026-001 §14.3.5 组件 A).
 *
 * <p>This is the bytecode-level counterpart to
 * {@code org.nebula.maintenance.MethodSignature} (which carries source-level
 * types like {@code "BlockState"}). The bytecode form keeps the raw JVM
 * descriptor because that's what ASM emits and what the {@code .class} file
 * is guaranteed to encode. The {@code simpleClassName} field is the de-obfuscated
 * equivalent of the binary name (e.g. {@code net/minecraft/world/entity/Entity}
 * → {@code Entity}) so reports can show readable output.
 *
 * <p>Identity for diff purposes is {@link #identityKey()}: owning class
 * (binary name) + method name + descriptor. Two methods with the same
 * identity key are "the same method" even if their access flags differ.
 *
 * @param ownerClass       internal binary name of the declaring class
 *                         (e.g. {@code net/minecraft/world/entity/Entity})
 * @param simpleClassName  last segment of {@code ownerClass} (e.g. {@code Entity})
 * @param methodName       the method's name (e.g. {@code tick})
 * @param descriptor       JVM descriptor (e.g. {@code (Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;)V})
 * @param access           raw access flags from the class file
 * @param signature        generic signature, or {@code null} if none
 */
public record BytecodeMethodDescriptor(
    String ownerClass,
    String simpleClassName,
    String methodName,
    String descriptor,
    int access,
    String signature
) {
    public BytecodeMethodDescriptor {
        Objects.requireNonNull(ownerClass, "ownerClass");
        Objects.requireNonNull(simpleClassName, "simpleClassName");
        Objects.requireNonNull(methodName, "methodName");
        Objects.requireNonNull(descriptor, "descriptor");
    }

    /** Identity key: owner#name descriptor. Used to match old/new pairs. */
    public String identityKey() {
        return ownerClass + "#" + methodName + " " + descriptor;
    }

    /** Key with the same shape as {@code MethodSignature.identityKey()} (owner#name(params)). */
    public String ownerNameKey() {
        return ownerClass + "#" + methodName + descriptor;
    }

    /** True iff this method is public. */
    public boolean isPublic() {
        return (access & java.lang.reflect.Modifier.PUBLIC) != 0;
    }

    /** True iff this method is private. */
    public boolean isPrivate() {
        return (access & java.lang.reflect.Modifier.PRIVATE) != 0;
    }

    /** True iff this method is protected. */
    public boolean isProtected() {
        return (access & java.lang.reflect.Modifier.PROTECTED) != 0;
    }

    /** True iff this method has package-private (default) visibility. */
    public boolean isPackagePrivate() {
        return !isPublic() && !isPrivate() && !isProtected();
    }

    /** True iff this method is static. */
    public boolean isStatic() {
        return (access & java.lang.reflect.Modifier.STATIC) != 0;
    }

    /** True iff this method is final. */
    public boolean isFinal() {
        return (access & java.lang.reflect.Modifier.FINAL) != 0;
    }

    /** True iff this method is a bridge method generated by the compiler. */
    public boolean isBridge() {
        return (access & org.objectweb.asm.Opcodes.ACC_BRIDGE) != 0;
    }

    /** True iff this method is synthetic (compiler-generated). */
    public boolean isSynthetic() {
        return (access & org.objectweb.asm.Opcodes.ACC_SYNTHETIC) != 0;
    }

    /** True iff this is a class initializer or instance initializer. */
    public boolean isInitializer() {
        return "<init>".equals(methodName) || "<clinit>".equals(methodName);
    }

    /** Visibility label suitable for reports: {@code public} / {@code protected} / {@code private} / {@code package}. */
    public String visibilityLabel() {
        if (isPublic()) return "public";
        if (isProtected()) return "protected";
        if (isPrivate()) return "private";
        return "package";
    }

    @Override
    public String toString() {
        return visibilityLabel()
            + (isStatic() ? " static" : "")
            + (isFinal() ? " final" : "")
            + " " + methodName + descriptor
            + "  (in " + simpleClassName + ")";
    }
}